# Generated by Django 5.0.7 on 2024-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="done",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="started",
            field=models.DateField(blank=True, null=True),
        ),
    ]
